### ISSUE TITLE
E056 Data sector corrupted, with 48496640 below map_size

### ISSUE THREAD

**Issue by tiandiyixian** [scanoss/minr#11]
I built the system with the latest master, but some projects have no problems, and some projects will report the following errors. What is the reason?
Importing quality.csv
mined//quality.csv
E056 Data sector corrupted, with 48496640 below map_size

minr -d spring-projects,spring-framework,v5.3.14,20171227,zlib,pkg:github/spring-projects/spring-framework -u https://hub.fastgit.org/spring-projects/spring-framework/archive/v5.3.14.zip
minr -z mined
minr -i mined/
or
minr -d torvalds,linux,v5.8,20171227,zlib,pkg:github/torvalds/linux -u https://hub.fastgit.org/torvalds/linux/archive/v5.8.zip , etc.

**Comment by mscasso-scanoss** [comment]
Hi @tiandiyixian. It looks like you haven't empty space in your hard disk. Could you please confirm that?

**Comment by tiandiyixian** [comment]
yes，space is not enough！thanks
