### ISSUE TITLE
build failure on Fedora 33

### ISSUE THREAD

**Issue by armijnhemel** [scanoss/minr#15]
Followed the instructions from `README.md`, but:

```
collect2: error: ld returned 1 exit status
make: *** [Makefile:24: minr] Error 1

```
This is with the latest `ldb` installed on the system. I noticed that the header file `ldb.h` is out of sync with `ldb`

**Comment by mscasso-scanoss** [comment]
Hi @armijnhemel ! It looks like ld isn't able to find the ldb.so shared library. This is all the message that you get? Have you already ran make && make install for the ldb repo?

**Comment by armijnhemel** [comment]
It is installed of course:

```
$ file /usr/lib/libldb.so 
/usr/lib/libldb.so: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, BuildID[sha1]=58211149ba1f63f79442e3ada0c5f364d9b5442b, with debug_info, not stripped
$ ll /usr/lib/libldb.so 
-rwxr-xr-x 1 root root 162416 Feb  8 20:56 /usr/lib/libldb.so
```

Another problem is that you have named your library the same as an existing library from Samba:

```
$ rpm -qfi /usr/lib64/libldb.so.2.2.2
Name        : libldb
Version     : 2.2.2
Release     : 1.fc33
Architecture: x86_64
Install Date: Fri 05 Nov 2021 11:35:13 AM CET
Group       : Unspecified
Size        : 572619
License     : LGPLv3+
Signature   : RSA/SHA256, Fri 29 Oct 2021 05:08:04 PM CEST, Key ID 49fd77499570ff31
Source RPM  : libldb-2.2.2-1.fc33.src.rpm
Build Date  : Fri 29 Oct 2021 02:28:24 PM CEST
Build Host  : buildvm-x86-11.iad2.fedoraproject.org
Packager    : Fedora Project
Vendor      : Fedora Project
URL         : http://ldb.samba.org/
Bug URL     : https://bugz.fedoraproject.org/libldb
Summary     : A schema-less, ldap like, API and database
Description :
An extensible library that implements an LDAP like API to access remote LDAP
servers, or use local tdb databases.
```

I would suggest that you rename your library.

**Comment by mscasso-scanoss** [comment]
Dear @armijnhemel could you try again? Please update both repositories from master (ldb and minr). I have done the test in my virtual machine with fedora 33 and it works fine despite the name of the ldb share library. Please let me know if it works for you. One you have built minr you are going to need to install some other dependencies like unrar and 7z.

**Comment by armijnhemel** [comment]
Initially this didn't work:
```
$ ldd minr 
	linux-vdso.so.1 (0x00007ffd35b45000)
	libz.so.1 => /lib64/libz.so.1 (0x00007f0ba4c4a000)
	libldb.so => not found
	libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f0ba4c28000)
	libcrypto.so.1.1 => /lib64/libcrypto.so.1.1 (0x00007f0ba493b000)
	libc.so.6 => /lib64/libc.so.6 (0x00007f0ba4770000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f0ba4c81000)
	libdl.so.2 => /lib64/libdl.so.2 (0x00007f0ba4769000)

```

but after running `ldconfig` it does. This is not ideal, you might want to look into cleaning this up.

**Comment by mscasso-scanoss** [comment]
Okay @armijnhemel , thanks you very much for answering. I didn't have that problem with LD in my VM. Anyway, I think your suggestion makes sense. I'm closing this issue and we can continue talking about that in the ldb repository issue
