### ISSUE TITLE
How to remove an imported project from database?

### ISSUE THREAD

**Issue by leoliaolei** [scanoss/minr#25]
When doing knowdge base housekeeping, we may need remove some previously imported data. 
I searched the document of minr and ldb but cannot find a way to do that.
For example, a project imported with `minr -d madler,pigz,2.4,20171227,zlib,pkg:github/madler/pigz -u https://github.com/madler/pigz/archive/v2.4.zip`. How can I totally remove its data from ldb?

**Comment by mscasso-scanoss** [comment]
Hi @leoliaolei, you can not remove a key from the KB using minr, you have to use the command `ldb delete` instead. I understand this is a bit confusing, next releases of the core software will move the import command from minr to ldb to be more consistent.
