### ISSUE TITLE
minr local folder error

### ISSUE THREAD

**Issue by xu1119** [scanoss/minr#29]
I followed steps from README and successfully installed minr.
I can minr from a url.
When I try to minr from  local folder, it can not run and get an error: 
> sh: 1: Syntax error: "(" unexpected

The command is:
> minr -d scanoss,ldb,3.1.5,20221017,gpl-2.0,pkg:github/scamoss/ldb -u ./ldb-3.1.5

* minr version: scanoss-minr-2.5.8
* ldb version: ldb-3.1.5
* os: ubuntu:20.04

How to solve the problem?

**Comment by mscasso-scanoss** [comment]
Dear @xu1119 Thank you for report this problem. You are missing one part of the command specifying the information you want to mine from the folder. For example, if you want to mine "licenses", your command should looks like:

`minr -d scanoss,ldb,3.1.5,20221017,gpl-2.0,pkg:github/scamoss/ldb -u ./ldb-3.1.5 -L./ldb-3.1.5`

From minr help - Local mining:

-L TARGET  Analyse file/directory (and sub directories) to detect license license declarations
-C TARGET  Analyse file/directory (and sub directories) to detect copyrigths
-Q TARGET  Analyse file/directory (and sub directories) for evaluating code quality
-Y TARGET  Analyse file/directory (and sub directories) to detect cryptographic algorithms usage.

**Comment by mscasso-scanoss** [comment]
HI, to generate the wfp you have to use the same command than for url mining. From minr help:
```

Mining snippet WFP: Minr extracts snippet fingerprint from all code in a .mz arhive (mined/sources/)
into mined/wfp/
-z DIRECTORY   Indicates the location of the mined/ directory
```

**Comment by xu1119** [comment]
Great, it can help me.
