### ISSUE TITLE
minr -i import data to target dir other than /var/lib/ldb/oss

### ISSUE THREAD

**Issue by DRong1121** [scanoss/minr#32]
<img width="1007" alt="image" src="https://github.com/scanoss/minr/assets/20332907/414cd12a-2cb7-44ee-a3ef-b089893ebf0b">

Hello, I have a question about minr importation,
Is it possible to import the /mined directory to another target dir other than /var/lib/lib/oss?
If it is possible, how to write the minr -i command? Thanks!

**Comment by superkaiy** [comment]
The option "-D" maybe meet your requirement. It will specified another database for storing the mining data, and you need to specify the KB database name on the client if you have scanning requests. But there is no options for supporting to specify the KB database name
`minr -i mined/ -D <string>`
